function pairs = default_content_types()
% DEFAULT_CONTENT_TYPES (extension, content-type) pairs eligible for a <Default>.
%
%   pairs = MAT2DOC.OPC.DEFAULT_CONTENT_TYPES() returns an Nx2 string array of
%   [extension, content_type] rows, in Python source order (H11).
%
%   CRITICAL SHAPE (spec.py is a DUPLICATE-KEY PAIR-LIST, NOT a dict): several
%   extensions map to more than one content type -- here `bin` appears THREE
%   times (printer-settings for pptx/xlsx/docx). Python consumes this as
%   `(ext.lower(), content_type) in default_content_types` (pkgwriter.py
%   _ContentTypesItem._add_content_type): BOTH fields of the pair must match for
%   a part to be classified as a <Default> rather than an <Override>. Porting
%   this as a containers.Map / dictionary keyed by extension would COLLAPSE the
%   three `bin` rows to one and silently break default-vs-override precedence
%   (an <Override> that should stay an <Override> could be mis-classified). It is
%   therefore an Nx2 row-list; membership is a ROW test (both columns), never a
%   key lookup. Membership is order-insensitive (a set-membership test in
%   Python), so row ORDER carries no behavior -- it is preserved only for
%   readability/audit.
%
%   Example:
%       pairs = mat2doc.opc.default_content_types();
%       CT = mat2doc.opc.CONTENT_TYPE;
%       % row-membership (the Python `(ext, ct) in default_content_types`):
%       is_default = any(pairs(:,1) == "png" & pairs(:,2) == CT.PNG);   % true
%
%   Ported from python-docx v1.2.0: src/docx/opc/spec.py::default_content_types
%   (lines 5-24)

CT = mat2doc.opc.CONTENT_TYPE;
pairs = [ ...
    "bin",     CT.PML_PRINTER_SETTINGS; ...
    "bin",     CT.SML_PRINTER_SETTINGS; ...
    "bin",     CT.WML_PRINTER_SETTINGS; ...
    "bmp",     CT.BMP; ...
    "emf",     CT.X_EMF; ...
    "fntdata", CT.X_FONTDATA; ...
    "gif",     CT.GIF; ...
    "jpe",     CT.JPEG; ...
    "jpeg",    CT.JPEG; ...
    "jpg",     CT.JPEG; ...
    "png",     CT.PNG; ...
    "rels",    CT.OPC_RELATIONSHIPS; ...
    "tif",     CT.TIFF; ...
    "tiff",    CT.TIFF; ...
    "wdp",     CT.MS_PHOTO; ...
    "wmf",     CT.X_WMF; ...
    "xlsx",    CT.SML_SHEET; ...
    "xml",     CT.XML];
end
