function outdocx = build_user_manual(outdocx)
% BUILD_USER_MANUAL  Generate the Mat2Doc User Manual -- BY Mat2Doc (dogfood).
%
%   outpath = BUILD_USER_MANUAL() builds the manual next to this file at
%   docs\manual\Mat2Doc_User_Manual.docx and returns its absolute path.
%
%   outpath = BUILD_USER_MANUAL(outdocx) writes to the given .docx path.
%
%   This is the FINAL P8-EXIT deliverable for the Mat2Doc port. The manual is
%   itself a Word .docx authored ENTIRELY through the Mat2Doc public API --
%   Mat2Doc documents itself. It exercises the breadth the system campaigns
%   proved: core properties; headings/Title; rich runs (bold/italic/underline/
%   double-underline, Pt size, font name, RGBColor); alignment; bulleted and
%   numbered lists; a styled table with a merged banner cell, populated cells,
%   and a set column width; an inline picture; a landscape section with distinct
%   margins, a header carrying text + a logo picture, a footer, and a different
%   first-page header; a page break; and a comment anchored to a run.
%
%   Run INLINE / FOREGROUND (never background a MATLAB run). It adds only the
%   Mat2Doc toolbox root to the path, builds the document, saves it, and prints
%   the saved path. No toolbox code is modified; nothing is committed.
%
%   Author: mso-doc-writer (Mat2Doc P8-EXIT dogfooded user manual).

    thisdir = fileparts(mfilename('fullpath'));                 % docs\manual
    toolboxroot = fileparts(fileparts(thisdir));                % repo root (holds +mat2doc)
    addpath(toolboxroot);

    if nargin < 1 || isempty(outdocx)
        outdocx = string(fullfile(thisdir, "Mat2Doc_User_Manual.docx"));
    else
        outdocx = string(outdocx);
    end

    % A small image bundled with the python-docx reference clone -- used as the
    % worked-example figure and as the header logo (same breadth the campaigns
    % proved: an inline body picture AND a header-part logo, de-duped).
    IMG = "C:\Users\dougl\Repos\python-docx\tests\test_files\python-powered.png";

    d = mat2doc.Document();                                     % open the bundled default template

    % ---- core (document) properties -----------------------------------------
    cp = d.core_properties;
    cp.author         = "Mat2Doc";
    cp.title          = "Mat2Doc User Manual";
    cp.subject        = "Authoring Word documents from base MATLAB";
    cp.category       = "Documentation";
    cp.keywords       = "mat2doc, python-docx, word, docx, matlab";
    cp.comments       = "This manual was generated by the Mat2Doc toolbox itself (dogfood).";
    cp.content_status = "Final";
    cp.language       = "en-US";

    % =========================================================================
    % TITLE PAGE
    % =========================================================================
    d.add_heading("Mat2Doc User Manual", 0);                    % Title
    sub = d.add_paragraph("Create Word documents from base MATLAB.", "Subtitle");
    sub.alignment = mat2doc.enum.text.WD_ALIGN_PARAGRAPH.LEFT; %#ok<NASGU>

    p = d.add_paragraph();
    r = p.add_run("A faithful MATLAB replica of python-docx v1.2.0.");
    r.italic = true;

    p = d.add_paragraph();
    r = p.add_run("This manual is itself a .docx file, and it was generated by " + ...
        "Mat2Doc. Every heading, paragraph, list, table, figure, header, footer, " + ...
        "and comment on the pages that follow was produced by the same public API " + ...
        "the manual describes. Mat2Doc documents itself.");
    r.bold = true;

    d.add_page_break();

    % =========================================================================
    % 1. INTRODUCTION
    % =========================================================================
    d.add_heading("1. Introduction", 1);
    d.add_paragraph( ...
        "Mat2Doc is an exact functional MATLAB port of python-docx v1.2.0. It " + ...
        "runs on base MATLAB R2024b with no additional toolboxes and produces " + ...
        "Office Open XML (.docx) packages that open cleanly in Microsoft Word. " + ...
        "The API mirrors python-docx symbol-for-symbol: a Document opens a " + ...
        "package, paragraphs and runs carry the text, and value types such as " + ...
        "Inches, Pt, and RGBColor express measurements and colour.");
    d.add_paragraph( ...
        "Because the port is validated at the XML-part level against python-docx, " + ...
        "a script written to this manual produces the same bytes a line-for-line " + ...
        "python-docx script would produce. See the closing chapter on the " + ...
        "equivalence guarantee.");

    d.add_heading("1.1 What you can build", 2);
    d.add_paragraph("Headings and a document Title", "List Bullet");
    d.add_paragraph("Rich text: bold, italic, underline, font, size, colour", "List Bullet");
    d.add_paragraph("Bulleted and numbered lists", "List Bullet");
    d.add_paragraph("Tables with styles, merged cells, and set column widths", "List Bullet");
    d.add_paragraph("Inline pictures", "List Bullet");
    d.add_paragraph("Sections with orientation, margins, headers, and footers", "List Bullet");
    d.add_paragraph("Comments anchored to a run of text", "List Bullet");

    % =========================================================================
    % 2. INSTALLATION & PATH SETUP
    % =========================================================================
    d.add_heading("2. Installation and Path Setup", 1);
    d.add_paragraph( ...
        "Mat2Doc ships as a MATLAB package folder (+mat2doc) inside the toolbox " + ...
        "root. Add that root to the MATLAB path, then reference everything through " + ...
        "the fully-qualified mat2doc.* namespace. There are no imports to manage " + ...
        "and no toolbox dependencies to install.");
    add_code(d, [ ...
        "% Point MATLAB at the folder that CONTAINS the +mat2doc package"
        "addpath('C:\Repos\Mat2Doc');"
        ""
        "% You are ready -- no 'import', no toolboxes"
        "d = mat2doc.Document();"]);
    d.add_paragraph( ...
        "Requirements: base MATLAB R2024b. No Report Generator, no other " + ...
        "toolboxes. The package uses only core MATLAB and the built-in Java ZIP " + ...
        "machinery for reading and writing the .docx container.", "Intense Quote");

    % =========================================================================
    % 3. QUICK START
    % =========================================================================
    d.add_heading("3. Quick Start", 1);
    d.add_paragraph( ...
        "The smallest useful program opens a document, writes a line, and saves. " + ...
        "mat2doc.Document() with no argument opens the bundled default template " + ...
        "(the same starting point as python-docx's Document()).");
    add_code(d, [ ...
        "d = mat2doc.Document();"
        "d.add_heading('Hello, Mat2Doc', 0);        % a Title"
        "d.add_paragraph('My first Word document.');"
        "d.save('hello.docx');"]);
    d.add_paragraph( ...
        "That produces a valid .docx that opens in Word with the Title and one " + ...
        "body paragraph. Everything else in this manual builds on those four lines.");

    % =========================================================================
    % 4. TEXT & FONTS
    % =========================================================================
    d.add_heading("4. Text and Fonts", 1);
    d.add_paragraph( ...
        "A paragraph is a sequence of runs. Each run carries its own character " + ...
        "formatting: bold, italic, underline, font name, size, and colour. Add an " + ...
        "empty paragraph, then append runs to it.");
    add_code(d, [ ...
        "p = d.add_paragraph();"
        "r = p.add_run('Bold ');    r.bold = true;"
        "r = p.add_run('italic ');  r.italic = true;"
        "r = p.add_run('underlined '); r.underline = true;"
        "r = p.add_run('double '); r.underline = mat2doc.enum.text.WD_UNDERLINE.DOUBLE;"
        "r = p.add_run('and 14pt red Consolas.');"
        "r.font.size       = mat2doc.shared.Pt(14);"
        "r.font.name       = 'Consolas';"
        "r.font.color.rgb  = mat2doc.shared.RGBColor(192, 0, 0);"]);
    d.add_paragraph("The code above produces this line:");
    p = d.add_paragraph();
    r = p.add_run("Bold ");                 r.bold = true;
    r = p.add_run("italic ");               r.italic = true;
    r = p.add_run("underlined ");           r.underline = true;
    r = p.add_run("double-underlined ");    r.underline = mat2doc.enum.text.WD_UNDERLINE.DOUBLE;
    r = p.add_run("and 14pt red Consolas.");
    r.font.size = mat2doc.shared.Pt(14);
    r.font.name = "Consolas";
    r.font.color.rgb = mat2doc.shared.RGBColor(192, 0, 0);
    demo_run = r;                                                % anchor for the comment chapter

    % =========================================================================
    % 5. PARAGRAPHS & STYLES
    % =========================================================================
    d.add_heading("5. Paragraphs and Styles", 1);
    d.add_paragraph( ...
        "Pass a style name as the second argument to add_paragraph to apply a " + ...
        "named paragraph style from the template (for example Quote or Intense " + ...
        "Quote). Set the alignment through the WD_ALIGN_PARAGRAPH enumeration.");
    add_code(d, [ ...
        "d.add_paragraph('A pull quote.', 'Quote');"
        "p = d.add_paragraph('Justified body text ...');"
        "p.alignment = mat2doc.enum.text.WD_ALIGN_PARAGRAPH.JUSTIFY;"]);
    d.add_paragraph("Rendered, the Quote style looks like this:");
    d.add_paragraph( ...
        "Simplicity is the soul of efficiency -- and a document that opens clean " + ...
        "is worth a thousand that need repair.", "Quote");
    p = d.add_paragraph( ...
        "This paragraph is justified: Mat2Doc writes the same w:jc element " + ...
        "python-docx would, so the text spreads evenly between the margins exactly " + ...
        "as Word expects. Alignment, indentation, and spacing all flow through the " + ...
        "same paragraph-format object.");
    p.alignment = mat2doc.enum.text.WD_ALIGN_PARAGRAPH.JUSTIFY;

    % =========================================================================
    % 6. LISTS & NUMBERING
    % =========================================================================
    d.add_heading("6. Lists and Numbering", 1);
    d.add_paragraph( ...
        "Bulleted and numbered lists are ordinary paragraphs with the List Bullet " + ...
        "or List Number style. Word supplies the bullet glyph or the running " + ...
        "number from the numbering definitions in the template.");
    add_code(d, [ ...
        "d.add_paragraph('Milk', 'List Bullet');"
        "d.add_paragraph('Eggs', 'List Bullet');"
        "d.add_paragraph('Preheat the oven', 'List Number');"
        "d.add_paragraph('Mix the batter',   'List Number');"]);
    d.add_paragraph("A bulleted list:");
    d.add_paragraph("Portable: base MATLAB, no toolboxes", "List Bullet");
    d.add_paragraph("Faithful: byte-validated against python-docx", "List Bullet");
    d.add_paragraph("Self-documenting: this manual proves it", "List Bullet");
    d.add_paragraph("A numbered procedure:");
    d.add_paragraph("Open a Document", "List Number");
    d.add_paragraph("Add content through the API", "List Number");
    d.add_paragraph("Save to a .docx path", "List Number");

    % =========================================================================
    % 7. TABLES
    % =========================================================================
    d.add_heading("7. Tables", 1);
    d.add_paragraph( ...
        "Create a grid with add_table(rows, cols), then apply a table style, set " + ...
        "the table alignment, merge cells, write cell text, and set column widths. " + ...
        "Collections such as columns are indexed 0-based through getitem_ to mirror " + ...
        "python-docx exactly.");
    add_code(d, [ ...
        "t = d.add_table(3, 3);"
        "t.style = 'Table Grid';"
        "t.alignment = mat2doc.enum.table.WD_TABLE_ALIGNMENT.CENTER;"
        "banner = t.cell(0,0).merge(t.cell(0,2));"
        "banner.text = 'FY2025 Results';"
        "t.cell(1,0).text = 'Quarter';"
        "t.columns.getitem_(0).width = mat2doc.shared.Inches(1.5);"]);
    d.add_paragraph("The resulting table:");
    t = d.add_table(3, 3);
    t.style = "Table Grid";
    t.alignment = mat2doc.enum.table.WD_TABLE_ALIGNMENT.CENTER;
    banner = t.cell(0, 0).merge(t.cell(0, 2));
    banner.text = "FY2025 Results";
    c = t.cell(1, 0); c.text = "Quarter";
    c = t.cell(1, 1); c.text = "Revenue";
    c = t.cell(1, 2); c.text = "Growth";
    c = t.cell(2, 0); c.text = "Q1";
    c = t.cell(2, 1); c.text = "$1.2M";
    c = t.cell(2, 2); c.text = "+4%";
    cols = t.columns; col0 = cols.getitem_(0);
    col0.width = mat2doc.shared.Inches(1.5);

    % =========================================================================
    % 8. IMAGES
    % =========================================================================
    d.add_heading("8. Images", 1);
    d.add_paragraph( ...
        "add_picture places an image in its own paragraph. Give a width (and " + ...
        "optionally a height) as a Length value type; omit them for the image's " + ...
        "native size. Mat2Doc registers the image part and its relationship the " + ...
        "same way python-docx does, and de-duplicates a repeated image.");
    add_code(d, [ ...
        "d.add_picture('logo.png', mat2doc.shared.Inches(2.0));"]);
    d.add_paragraph("An inline picture, sized to two inches wide:");
    d.add_picture(char(IMG), mat2doc.shared.Inches(2.0));

    % =========================================================================
    % 9. SECTIONS, HEADERS & FOOTERS
    % =========================================================================
    d.add_heading("9. Sections, Headers, and Footers", 1);
    d.add_paragraph( ...
        "A section controls page geometry -- orientation, size, and margins -- and " + ...
        "owns the header and footer. Start a new section, switch it to landscape, " + ...
        "set the margins, and turn on a distinct first-page header. Populate the " + ...
        "primary header with text and even a logo picture, and give the footer a " + ...
        "line of text.");
    add_code(d, [ ...
        "sec = d.add_section(mat2doc.enum.section.WD_SECTION.NEW_PAGE);"
        "sec.orientation = mat2doc.enum.section.WD_ORIENTATION.LANDSCAPE;"
        "sec.page_width  = mat2doc.shared.Inches(11);"
        "sec.page_height = mat2doc.shared.Inches(8.5);"
        "sec.different_first_page_header_footer = true;"
        "hp = sec.header.paragraphs(1);"
        "hp.text = 'Mat2Doc Showcase';"
        "hp.add_run().add_picture('logo.png', mat2doc.shared.Inches(0.5));"
        "sec.footer.paragraphs(1).text = 'Confidential - Page footer';"]);
    d.add_paragraph( ...
        "The next section of THIS manual is exactly that: a landscape page with a " + ...
        "header bearing a logo and a footer. Turn the page to see it live.");

    sec = d.add_section(mat2doc.enum.section.WD_SECTION.NEW_PAGE);
    sec.orientation = mat2doc.enum.section.WD_ORIENTATION.LANDSCAPE;
    sec.page_width = mat2doc.shared.Inches(11);
    sec.page_height = mat2doc.shared.Inches(8.5);
    sec.left_margin = mat2doc.shared.Inches(1.0);
    sec.right_margin = mat2doc.shared.Inches(1.0);
    sec.top_margin = mat2doc.shared.Inches(0.75);
    sec.bottom_margin = mat2doc.shared.Inches(0.75);
    sec.different_first_page_header_footer = true;

    header = sec.header;
    header.is_linked_to_previous = false;
    hps = header.paragraphs; hp = hps(1);
    hp.text = "Mat2Doc User Manual - Landscape Section";
    hr = hp.add_run();
    hr.add_picture(char(IMG), mat2doc.shared.Inches(0.4));

    footer = sec.footer;
    footer.is_linked_to_previous = false;
    fps = footer.paragraphs; fps(1).text = "Generated by Mat2Doc - Confidential";

    fph = sec.first_page_header;
    fph.is_linked_to_previous = false;
    fphs = fph.paragraphs; fphs(1).text = "First-page header (distinct from the primary header)";

    d.add_heading("9.1 This is the landscape section", 2);
    d.add_paragraph( ...
        "This page is landscape, with three-quarter-inch top and bottom margins, a " + ...
        "primary header that carries both text and a logo picture, a footer, and a " + ...
        "different first-page header. Every one of those was set with the code on " + ...
        "the previous page.");

    % =========================================================================
    % 10. COMMENTS
    % =========================================================================
    d.add_heading("10. Comments", 1);
    d.add_paragraph( ...
        "add_comment anchors a review comment to one or more runs. Pass the run to " + ...
        "anchor, the comment text, an author, and initials. Word shows the comment " + ...
        "in the margin against the highlighted range.");
    add_code(d, [ ...
        "r = p.add_run('figures to confirm');"
        "d.add_comment(r, 'Confirm before publication.', 'Reviewer', 'RV');"]);
    d.add_paragraph( ...
        "This manual anchors a real comment to the red Consolas sample back in the " + ...
        "Text and Fonts chapter -- open the manual in Word and the comment appears " + ...
        "in the review pane.");
    d.add_comment(demo_run, ...
        "This colored run is the live comment anchor demonstrated in Chapter 10.", ...
        "Mat2Doc", "M2D");

    % =========================================================================
    % 11. PYTHON-DOCX -> MAT2DOC CHEAT-SHEET
    % =========================================================================
    d.add_heading("11. python-docx to Mat2Doc Cheat-Sheet", 1);
    d.add_paragraph( ...
        "If you know python-docx, you already know Mat2Doc. These are the handful " + ...
        "of idiom translations that come up in practice.");
    idioms = [ ...
        "python-docx",                         "Mat2Doc";
        "from docx import Document",           "(no import; add the toolbox to the path)";
        "Document()",                          "mat2doc.Document()";
        "None",                                "[]  (the empty double)";
        "RGBColor(0xC0, 0x00, 0x00)",          "mat2doc.shared.RGBColor(192, 0, 0)";
        "Inches(1.5) / Pt(14)",                "mat2doc.shared.Inches(1.5) / mat2doc.shared.Pt(14)";
        "WD_ALIGN_PARAGRAPH.JUSTIFY",          "mat2doc.enum.text.WD_ALIGN_PARAGRAPH.JUSTIFY";
        "t.columns[0]  (0-based)",             "t.columns.getitem_(0)  (0-based getitem_)";
        "header.paragraphs[0]",                "header.paragraphs(1)  (native array, 1-based)";
        "runs[-1]",                            "runs(end)"];
    nrow = size(idioms, 1);
    ct = d.add_table(nrow, 2);
    ct.style = "Table Grid";
    for i = 1:nrow
        ci = ct.cell(i-1, 0); ci.text = idioms(i, 1);          % getitem_ semantics: 0-based cell(r,c)
        ci = ct.cell(i-1, 1); ci.text = idioms(i, 2);
    end
    d.add_paragraph( ...
        "Two rules cover almost everything else: fully-qualify names (there is no " + ...
        "import, so write mat2doc.shared.Pt, not Pt), and remember that library " + ...
        "collections keep python-docx's 0-based getitem_ while plain MATLAB arrays " + ...
        "returned to you are 1-based. When in doubt, getitem_ mirrors Python.");

    % =========================================================================
    % 12. THE EQUIVALENCE GUARANTEE
    % =========================================================================
    d.add_heading("12. The Equivalence Guarantee", 1);
    d.add_paragraph( ...
        "Mat2Doc is not merely inspired by python-docx -- it is validated against " + ...
        "it. For every work package, paired MATLAB and python-docx scripts build " + ...
        "the same document and their saved packages are compared part by part " + ...
        "after unzip. The expectation, met throughout the port, is that every XML " + ...
        "part is byte-identical (part-level L1) and every image part is identical.");
    d.add_paragraph( ...
        "The port carries zero output-visible deviations: no D-numbers were needed " + ...
        "to explain a difference in the bytes Mat2Doc writes versus python-docx " + ...
        "v1.2.0. The whole document you are reading was produced this way and " + ...
        "opens clean in real Microsoft Word.", "Intense Quote");
    d.add_paragraph( ...
        "Practically, that means you can prototype in python-docx and port to " + ...
        "Mat2Doc (or the reverse) with confidence that the output file is the " + ...
        "same. This manual -- generated by Mat2Doc itself -- is the proof.");

    % ---- save ---------------------------------------------------------------
    d.save(char(outdocx));
    fprintf("Mat2Doc User Manual saved: %s\n", outdocx);
end

% =============================================================================
function add_code(d, lines)
% ADD_CODE  Append a monospace code block: one paragraph, Consolas 9pt, with a
%   soft line break between source lines. Dogfoods add_run + font + add_break.
    p = d.add_paragraph();
    n = numel(lines);
    for i = 1:n
        r = p.add_run(lines(i));
        r.font.name = "Consolas";
        r.font.size = mat2doc.shared.Pt(9);
        if i < n
            r.add_break(mat2doc.enum.text.WD_BREAK.LINE);
        end
    end
end
